\context ChordNames	\chords {
	\set majorSevenSymbol = \markup { "maj7" }
	% intro
	a2:m a2:m

	%
	a2:m d2:m g2 c2
	a2:m d2:m e2:7 a2:m

	%
	a2:m d2:m g2 c2
	a2:m d2:m e2:7 a2:m

	%
	a2:7 d2:m g2 c2
	a2:m d2:m e2:7 a2:m

	%
	a2:7 d2:m g2 c2
	a2:m d2:m e2:7 a2:m a2:m

	%
	a2:m d2:m g2 c2
	a2:m d2:m e2:7 a2:m

	%
	a2:7 d2:m g2 c2
	a2:m d2:m e2:7 a2:m

	%
	a2:7 d2:m g2 c2
	a2:m d2:m e2:7 a2:m a2:m

}
